name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The type of runner that the job will run on

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          sudo systemctl start gunicorn
          cd /home/centos/address_book_app_be
          git pull

          sudo systemctl start gunicorn
